# Generated by Django 4.2.30 on 2026-04-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menucategory_menuitem_order_restaurant_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='display_order',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
